# permissions for end users to edit deploymentoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deploymentoperators-editor-role
rules:
- apiGroups:
  - apps.my.domain
  resources:
  - deploymentoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.my.domain
  resources:
  - deploymentoperators/status
  verbs:
  - get
